### ISSUE TITLE
Getting "XMLHttpRequest error." in Flutter Web

### ISSUE THREAD

**Issue by moazelsawaf** [lecuivre-alban/simple_gql#2]
Hello

I'm getting the following error every time I try to use the package in Flutter web while the same code is working fine in the mobile:

unknown error. Usually due to a bad URL or problem with the connection
XMLHttpRequest error.

**Comment by lecuivre-alban** [comment]
Hi, and sorry for the late response.
Thank you for letting me know about this issue. I also get the error and will look into it.
I'll keep you updated when I'm done with the fixing !

**Comment by moazelsawaf** [comment]
No problem,
 I have discovered the reason behind the problem, it was about a feature called CORS in the backend.
